### ISSUE TITLE
Ability to completely hide the chip photo

### ISSUE THREAD

**Issue by ogamespec** [msinger/dmg_cpu_b_map#2]
After getting the netlist, the chip picture becomes almost useless. It would be good to add a setting to look at the netlist without a picture.

![image](https://github.com/msinger/dmg_cpu_b_map/assets/5828819/dcc95802-861e-48c7-8792-01d4df1f8924)

**Comment by msinger** [comment]
Good idea! I'll look what I can do. :)

**Comment by msinger** [comment]
I added the option. You can also open the map directly without background by adding the GET parameter `?shot=-1`to the URL:
http://iceboy.a-singer.de/dmg_cpu_b_map/?shot=-1

Also works for the SM83 map.

**Comment by ogamespec** [comment]
Changed `map` div background-color to `grey`, looks great to me:

![image](https://github.com/msinger/dmg_cpu_b_map/assets/5828819/d960d1e3-f1af-4185-9dc1-d436905ea8ed)

**Comment by msinger** [comment]
Yes, that's much better. Thanks.
